PR : Release SPAShip
spaship/spaship-manager pull request #1
Opened 2021-08-16 06:16 UTC by soumyadip007

2021-08-16 08:28 UTC, arkaprovob commented
I will take a look and merge.

2021-08-16 09:22 UTC, arkaprovob commented
@soumyadip007 setup instruction is missing, Please modify the readme file remove existing content and just add basic instructions to set up and run this app

2021-08-16 10:22 UTC, soumyadip007 commented
@arkaprovob , I've modified the README.md. We need the Router and Manager UI using that.

2021-08-16 12:52 UTC, arkaprovob requested changes
Also mention 

- the usage of the router and common package
- please add more details on setup CLI and spaship-manager separately .
-  there are readme files inside individual packages as well. Would you please check them and make changes accordingly?

2021-08-20 14:20 UTC, arkaprovob requested changes
Please check my comments and resolve them.

2021-08-23 07:32 UTC, soumyadip007 commented on packages/manager-ui/src/components/property/NewRepositoryConfigs.tsx
> +      axios.get(`https://api.github.com/repos/soumyadipXD/spaship-spas/branches`)
NewRepositoryConfig was an redundant file, removed from the project.

2021-08-23 07:35 UTC, soumyadip007 commented on packages/manager/controllers/websites/gitOperations/gitOperations.js
> +    return Git.Signature.now("Soumyadip Chowdhury",
I've added spaship-deployment as the signature

2021-08-23 07:36 UTC, soumyadip007 commented on packages/manager/controllers/websites/gitOperations/gitOperations.js
> +    let remoteGitURL = "ssh://git@xxxxxx/home/git/git_test_repo.git";
Unused variables, removed.

2021-08-23 07:36 UTC, soumyadip007 commented on packages/manager/controllers/websites/gitOperations/gitOperations.js
> +                    return repo.getReferenceCommit('refs/remotes/origin/' + remoteBranch);
It'll work for commits. Sure

2021-08-23 07:41 UTC, soumyadip007 commented on packages/manager/controllers/websites/gitOperations/gitOperations.js
> +    res.send({ actionStatus: "Git Actions Performed Successfully", path: path.resolve(__dirname, `./../../../root/${directoryName}.zip`), websiteResponse : websiteResponse });
const basePath = config.get("directoryBasePath");
const resolvePathCreateBranch = `../../../${basePath}/${directoryName}/.git`;

Reading from ENV.

2021-08-23 07:47 UTC, arkaprovob commented on packages/manager/controllers/websites/gitOperations/gitOperations.js
> +    await zip(path.resolve(__dirname, `./../../../root/${directoryName}`), path.resolve(__dirname, `./../../../root/${directoryName}.zip`));
@soumyadip007 save it in a named directory example /apps/zip and add an env support for the location

2021-08-23 08:20 UTC, arkaprovob commented
Everything looks good, in next to get rid of all dotted directory navigation.

2021-08-23 08:21 UTC, merged